const MAP_INFO = {
  NEVISH_LINE: {
    name: 'Nevish Line',
    locations: [
      'The Aging Ocean',
      'The Arrow',
      'Blackcoat Way',
      'Blinding Stones',
      'Grief Mother',
      'Mistle Shrine',
      'Nevish Trail',
      'Plumage',
      'Princefal',
      'Princefal Burn',
      'The Scrying Belt',
      'Tear Road',
      'Tomb Father',
      'Unruly',
    ],
  },
  THE_OARBREAKER_ISLES: {
    name: 'The Oarbreaker Isles',
    locations: [
      'Alabastor Island',
      'Barrenson',
      'Base Akris',
      'Bronze',
      'Castor',
      'The Conclave',
      'Crach Woods',
      'Damsel',
      'The Dirk',
      'The Emblem',
      'Fogwood',
      'Gold',
      'Grisly Refuge',
      'The Ides',
      'Integrum',
      'Kofteri Channel',
      "Lion's Head",
      'Martius',
      'Mount Marce',
      "Neptune's Throne",
      'Oasis',
      'Oblitum',
      'Pollux',
      'Posterus',
      "Raven's Beak Fort",
      'Reliqua',
      'Sandalwood Beach',
      'Silver',
      'Skelter Course',
      'Skull Beach',
      'Thunder Row',
    ],
  },
  FISHERMANS_ROW: {
    name: "Fisherman's Row",
    locations: [
      'A Lost Sot',
      'Arcadia',
      'Bident Crossroads',
      'Black Well',
      'Cat Step',
      'Dankana Post',
      'The Dire Strings',
      'Eidolo',
      'Fort Ember',
      "Hangmen's Court",
      'Heart of Rites',
      'House Roloi',
      'Lake Nerites',
      'Liberty Hill',
      'Oceanwatch',
      'Partisan Island',
      'Peripti Landing',
      'Progonos Watch',
      'The Rite Road',
      'The Satyr Stones',
      'The Three Sisters',
      'Torch of Demeter',
    ],
  },
  ORIGIN: {
    name: 'Origin',
    locations: [
      'Arise',
      'Cado',
      'Dormio',
      "The Dreamer's Road",
      'The Echo',
      'Exorior',
      'Finis',
      'Initium',
      'The Sundering',
      'Teichotima',
      'Temple Field',
      'World Star',
    ],
  },
  CALLUMS_CAPE: {
    name: "Callum's Cape",
    locations: [
      "Callum's Keep",
      'Camp Hollow',
      'The Dreg',
      'The Gunwall',
      'Holdout',
      'Hollowhill',
      'Ire',
      'Lookout',
      'Naofa',
      'Princefal Burn',
      'The River Vein',
      'Scouts Jest',
      'Trail of the Dead',
      'Valta Downs',
    ],
  },
  STONECRADLE: {
    name: 'Stonecradle',
    locations: [
      'The Agiing Ocean',
      'Buckler Sound',
      'The Cord',
      'Fading Lights',
      "The Heir's Knife",
      'The Loneliest Shore',
      'The Long Fast',
      'Longing',
      'The Pram',
      'The Reach',
      'The Roiling Comets',
      'Trammel Pool',
      "World's End",
    ],
  },
  FARRANAC_COAST: {
    name: 'Farranac Coast',
    locations: [
      "Apollo's Landing",
      'The Bay of Artemis',
      'The Bone Haft',
      'Carrion Fields',
      'Cormac Beach',
      'Gulf of the Daughters',
      'The Heart Road',
      'Hermes Inlet',
      'Huskhollow',
      'The Iron Beach',
      'Iuxta Homestead',
      'The Jade Cove',
      'Kardia',
      'Liberation Street',
      'Lushlands',
      "Macha's Keening",
      'Mara',
      'McCarthy Fields',
      'The Mirror',
      'Mooring Dens',
      'Pleading Wharf',
      'The Reaping Fields',
      'The River Mercy',
      'Scarp of Ambrose',
      'Scythe',
      'Sickle Hill',
      'Skeleton Road',
      'The Snag',
      'The Spearhead',
      'Sunder Beach',
      'Terra',
      'Transient Valley',
      'Victa',
      'The Winged Walk',
    ],
  },
  WESTGATE: {
    name: 'Westgate',
    locations: [
      'The Aging Ocean',
      'Ash Step',
      'Candle Hills',
      'Cattle March',
      'Ceo Highlands',
      'Cinder Road',
      'Coasthill',
      'Coastway',
      "Cobber's Lane",
      'The Divide',
      'Ember Hills',
      "Fand's Chain",
      'Fields of Badb',
      "Flidais' Pasture",
      'The Gallows',
      'Handsome Hideaway',
      'The Hem',
      'Hillcrest',
      'Holdfast',
      'Inkwell Lane',
      'Kardia Road',
      'Killian Quarter',
      "The King's Road",
      'Kingstone',
      "The Knight's Edge",
      'Longstone',
      "Lord's Mouth",
      'Lost Partition',
      "Rancher's Fast",
      "Reaver's Cove",
      'Sanctified Path',
      'Sanctuary',
      'Síochána Valley',
      'Taswell Point',
      "Triton's Curse",
      'Warden Walk',
      'Western Heartlands',
      'Westgate Keep',
      'Wire Road',
      'Wyattwick',
      "Zeus' Demise",
    ],
  },
  ASH_FIELDS: {
    name: 'Ash Fields',
    locations: [
      'Ash Step',
      'The Ashfort',
      'Ashtown',
      'The Calamity',
      'Camp Omega',
      'Cinder Road',
      'Cometa',
      'Electi',
      'Ember Hills',
      "Gunslinger's Pass",
      'Mount Blackmoth',
      'Mount Brimstone',
      'Omega Valley',
      'The Red River',
      'Sootflow',
      'The Stillness',
      'Tar Creek',
      'Twin Flames',
      'Wasteful Calm',
    ],
  },
  SPEAKING_WOODS: {
    name: 'Speaking Woods',
    locations: [
      'Calmland',
      'Cursed Court',
      'The Filament',
      'Fort Blather',
      'Hush',
      'Inari Base',
      'Mount Rell',
      'Mute',
      'Reaching River',
      'Rell Foothills',
      'Sotto Bank',
      'Stem',
      'Tine',
      'Wound',
    ],
  },
  THE_MOORS: {
    name: 'The Moors',
    locations: [
      "Aillen's Burrow",
      'Bitter Bramble',
      'Borderlane',
      "Callum's Pass",
      'The Cut',
      'The Finger',
      'The Graveyard',
      'Headstone',
      "Luch's Workshop",
      "Lyon's Wood",
      'MacConmara Barrows',
      "Moon's Walk",
      "Morrighan's Grave",
      'The Mound',
      'Ogmaran',
      'Reaching River',
      'Riverhill',
      'Scáth Copse',
      'Wiccwalk',
      'Wiccwood',
      'The Wind Hills',
    ],
  },
  THE_LINN_OF_MERCY: {
    name: 'The Linn of Mercy',
    locations: [
      'Blackroad',
      'The Crimson Gardens',
      'The Drone',
      'The First Coin',
      'Fort Duncan',
      'Gallant Gough Boulevard',
      'The Great Scale',
      'Hardline',
      'The Last Grove',
      'Lathair',
      'The Long Whine',
      'Merciful Strait',
      'Mudhole',
      'Nathair',
      'Outwich Ranch',
      'The Prairie Bazaar',
      'The River Mercy',
      'Rotdust',
      'Solas Burn',
      'Ulster Falls',
    ],
  },
  LOCH_MOR: {
    name: 'Loch Mor',
    locations: [
      "Bastard's Blade",
      'Chattering Prairie',
      'Escape',
      'Fallen Fields',
      'Feirmor',
      'The Founding Fields',
      'The Glean',
      'Loch Mor',
      'Market Road',
      "Mercy's Wish",
      'Missing Bones',
      "Moon's Copse",
      'Ousterdown',
      'Pockfields',
      'The Reaping Road',
      'Rip',
      'The Roilfort',
      'Tear',
      'Tomb of the First',
      'Westmarch',
      "Widow's Wail",
    ],
  },
  THE_HEARTLANDS: {
    name: 'The Heartlands',
    locations: [
      '18th Sideroad',
      'Barronstown',
      'Barronswall',
      'Barrony Ranch',
      'Barrony Road',
      'The Blemish',
      'The Breach',
      'Cageroad',
      'Crater Basin',
      'Deeplaw Post',
      'Erimos Ranch',
      'Fort Providence',
      'The Fuming Pen',
      'Greenfield Orchard',
      "Havester's Range",
      'Janus Field',
      'Kos Meadows',
      'Loftmire',
      'Lower Barrony Field',
      'Oleander Fields',
      'Oleander Homestead',
      'Pandora Compound',
      'The Plough',
      'Proexí',
      'Providence Field',
      'The Rollcage',
      'The Salt Crossing',
      'Upper Barrony Field',
      'Upper Heartlands',
    ],
  },
  RED_RIVER: {
    name: 'Red River',
    locations: [
      'Camp Upsilon',
      'Cannonsmoke',
      'Climb',
      'Fort Matchwood',
      'Fragment Knolls',
      'Gunpowder Lane',
      'Judicium',
      'Minos',
      'Penance',
      'Perish',
      'Red Crossing',
      'The Red River',
      'Twelve Drops',
      'Victoria Hill',
    ],
  },
  BASIN_SIONNACH: {
    name: 'Basin Sionnach',
    locations: [
      'Basin Sionnach',
      'Basinhome',
      'Cunning Cross',
      'Cuttail Station',
      'The Den',
      'The Foxfields',
      'Lamplight',
      'Radiant Shore',
      'Sess',
      'Stoic',
    ],
  },
  REACHING_TRAIL: {
    name: 'Reaching Trail',
    locations: [
      'Windy Way',
      'The Ark',
      'The Bait',
      'Brodytown',
      'The Cairns',
      'Camp Eos',
      'Caragtais',
      'The Chicken Coop',
      'The Deckard',
      "Duffy's Farm",
      "Dungan's Approach",
      'Dwyersfield',
      'Dwyerstown',
      'Elksford',
      'Featherfield',
      "Fisherman's Floe",
      'Harpy',
      'Hookhall',
      'Humidus',
      'Ice Ranch',
      'The Knot',
      'Limestone Holdfast',
      "Mac Conaill's Pass",
      'Mousetrap',
      'Nightchurch',
      'Pitfall',
      'Puncta',
      'The Reaching Heights',
      'Reprieve',
      'The Rousing Fields',
      'The Scar',
      'Scorpion',
      'Thýlak',
    ],
  },
  CALLAHANS_PASSAGE: {
    name: "Callahan's Passage",
    locations: [
      "Callahan's Eye",
      'Chapel Access',
      'Cragsfield',
      'Cragsroad',
      'Cragstown',
      'The Crumbling Passage',
      'Crumbling Post',
      'The Key',
      'The Lance',
      'The Latch',
      'Lingering Lashes',
      'Lochan',
      'Lochan Berth',
      'Lost Tops',
      'Overlook Hill',
      'The Procession',
      'The Rust Road',
      'Scáth Passing',
      'Sioc Approach',
      'Solas Gateway',
      'Solas Gorge',
      'Soured Fields',
      'The Stern',
      'Twisted Mumble',
      'White Chapel',
      'Winding Crag',
    ],
  },
  DEADLANDS: {
    name: 'Deadlands',
    locations: [
      'Abandoned Ward',
      'The Abbey Drag',
      'The Blade',
      'The Boneyard',
      'Border Concourse',
      'Border Thicket',
      'Brine Glen',
      "Callahan's Boot",
      "Callahan's Gate",
      "Callahan's Pass",
      'Carpal Trail',
      'Cemetary Junction',
      'Cemetary Lane',
      'The Crossing',
      'Crumbling Passage',
      'The Great March',
      "Hope's Causeway",
      'The Iron Passage',
      'The Iron Road',
      "Iron's End",
      'Jaspar Range',
      'Liberation Point',
      'Mandible Crossroads',
      'Marrow Copse',
      'Mercy Meadow',
      "Mercy's End",
      'Overgrown Pasture',
      'Path to the Sun',
      'The Pits',
      'The Plaza',
      'Pommel Annex',
      'The Salt Farms',
      'The Salt March',
      'The Salt Trail',
      'The Shorn Fields',
      'The Spine',
      'The Steppes',
      "Sun's Hollow",
      'Sunhaven Gateway',
      'Tarsal Pathway',
      '',
    ],
  },
  UMBRAL_WILDWOOD: {
    name: 'Umbral Wildwood',
    locations: [
      'Adze Crossroads',
      'Amethyst',
      "Atropos' Fate",
      "Clotho's Refuge",
      'Dredgefield',
      'The Dredgewood',
      'The Foundry',
      'The Frontier',
      'The Gap',
      'Golden Concourse',
      'GoldenRoot Ranch',
      "Hermit's Rest",
      "Lachesis' Tally",
      'Leatherback Pathway',
      'Sentry',
      'Steely Fields',
      'The Strands',
      'Stray',
      'Terrapin Woods',
      'Thunder Row',
      'Thunderfoot',
      'Vagrant Bastion',
      'Wasting Holt',
      "Weaver's Trail",
    ],
  },
  GREAT_MARCH: {
    name: 'Great March',
    locations: [
      'The Black Wing',
      'Dalton Meadow',
      'Dendró Field',
      'Eristown',
      'Fateless Grove',
      'Fengari',
      'The Great March',
      'Halting Valley',
      'Jackboot Creek',
      'Legacy Pasture',
      'Leto',
      'The Midmarch',
      'Milowood',
      'Mors Range',
      "Myrmidon's Stay",
      'Remnant Acreage',
      'Remnant Villa',
      'The River Senti',
      'Schala Estate',
      'Scrabbling Motte',
      'Serpent Charm',
      'Sitaria',
      'The Spice Road',
      'The Swan',
      'Violet Fields',
      'Violethome',
      'The White Wing',
      'Zealous Approach',
    ],
  },
  KALOKAI: {
    name: 'Kalokai',
    locations: [
      'Baccae Ridge',
      'Bleary',
      'Camp Tau',
      'Clarity Meadow',
      'Hallow',
      'Lost Greensward',
      "Night's Regret",
      'Sourtooth',
      'South March',
      'Sweethearth',
      'The Stumble',
      'The Vineroad',
      'Vinum Rillet',
    ],
  },
  HOWL_COUNTY: {
    name: 'Howl County',
    locations: [
      'Austriaca Reservoir',
      'Checkpoint Titim',
      'Fort Red',
      'Fort Rider',
      'Great Warden Dam',
      'Hungry Wolf',
      'Little Lamb',
      'Sickleshire',
      'Slipgate Outpost',
      'Snakewell',
      'Teller Farm',
      'The Hunting Grounds',
      'Viperwalk',
    ],
  },
  VIPER_PIT: {
    name: 'Viper Pit',
    locations: [
      "Afric's Approach",
      'Austriaca River',
      'Blackthroat',
      'The Bloody Bowery',
      'Deadsteps',
      'Earl Crowley',
      "Earl's Welcome",
      'Fleck Crossing',
      'Fort Viper',
      'The Friars',
      'Hardcaps',
      'Kirknell',
      "The Lady's Lake",
      'Lake Mioira',
      'Moltworth',
      'Path of the Charmed',
      'The Rockaway',
      "Serenity's Blight",
      'The Slithering Scales',
      'Snakehead Lake',
      'The Tongue',
      'Twin Fangs',
    ],
  },
  MARBAN_HOLLOW: {
    name: 'Marban Hollow',
    locations: [
      'Bleating Plateau',
      'Bubble Basin',
      'Checkpoint Bua',
      'The Clutch',
      'The Curse',
      'Deepfleet Valley',
      'Gaping Maw',
      'Lockheed',
      'Lockheed Breakers',
      'Lughbone Dam',
      "Maiden's Veil",
      'Mount Mac Tire',
      'Mox',
      'Oster Wall',
      'Pilgrimage',
      'The Claim',
      'Sanctum',
      'Slender Cove',
      'The Spitrocks',
    ],
  },
  THE_DROWNED_VALE: {
    name: 'The Drowned Vale',
    locations: [
      'The Baths',
      'Bootnap',
      'Coaldrifter Stead',
      'Eastmarch',
      'Esterfal',
      'Fleetsfall River',
      'Loggerhead',
      'The Other Vein',
      'The Saltcaps',
      'Singing Serpents',
      'Sop Fields',
      'Splinter Pens',
      "Sprite's Game",
      'The Turtlerocks',
      'The Wash',
      'The Willow Wood',
      "Wisp's Warning",
    ],
  },
  SHACKLED_CHASM: {
    name: 'Shackled Chasm',
    locations: [
      'A Careless Net',
      'A New Spring',
      'Autumn Pyres',
      'The Bell Toll',
      'The Blue',
      'Final Step',
      'The First Rung',
      'Firstmarch',
      'The Foolish Maidens',
      'Gorgon Grove',
      'The Grave of Rastus',
      'Hades Ladder',
      "Legion's Dawn",
      'Manky Hills',
      'The Plunging',
      'Reflection',
      'Silk Farms',
      "Simo's Run",
      'Southreach',
      'The Vanguard',
      "Widow's Web",
    ],
  },
  ACRITHIA: {
    name: 'Acrithia',
    locations: [
      "Astero's Spear",
      'The Brinehold',
      'Camp Omnicron',
      'Duelling Kegs',
      'Fated Heel',
      'Final March',
      'Heir Apparent',
      'Legion Ranch',
      'Nereid Keep',
      'Patridia',
      'Riverlands',
      'Swordfort',
      'Thetus Ring',
      'Weary Slumber',
    ],
  },
  CLANSHEAD_VALLEY: {
    name: 'Clanshead Valley',
    locations: [
      "The Bastard's Channel",
      'Bramble Field',
      'Fallen Crown',
      'Fort Ealar',
      'Fort Esterwild',
      'The King',
      'Lost Orphans',
      'ort Windham',
      'The Pike',
      'Sweetholt',
      'Tallowild',
      'Throne of Druiminn',
      'The Weathered Expanse',
    ],
  },
  WEATHERED_EXPANSE: {
    name: 'Weathered Expanse',
    locations: [
      'Bannerwatch',
      'Barrowsfield',
      "Crow's Nest",
      "Dullahan's Crest",
      'Eapoe',
      'Foxcatcher',
      'Frostmarch',
      'Huntsfort',
      'The Ivory Bank',
      'The Ivory Sea',
      'Kirkyard',
      'Necropolis',
      'Port of Rime',
      "Revenant's Path",
      'Rime Wastes',
      'Shattered Advance',
      'The Spear',
      'Spirit Watch',
      'The Stand',
      'The Weathered Wall',
      'The Weathering Halls',
      'Wightwalk',
      "Wraith's Gate",
    ],
  },
  ENDLESS_SHORE: {
    name: 'Endless Shore',
    locations: [
      "Balor's Crown",
      'Brackish Point',
      'The Dannan Coast',
      'Dannan Ridge',
      'The Dark Road',
      "Dearg's Fang",
      'Enduring Wake',
      'The Evil Eye',
      'Iron Junction',
      "Kelpie's Mane",
      "Kelpie's Tail",
      "Merrow's Rest",
      'The North Star',
      'The Old Jack Tar',
      'The Overland',
      'Saltbrook Channel',
      'The Selkie Bluffs',
      'Sídhe Fall',
      'The Styx',
      'Tuath Watchpost',
      'Vulpine Watch',
      'Weakthered Landing',
      'Wellchurch',
      'The Whispering Waves',
      'Woodbind',
    ],
  },
  ALLODS_BIGHT: {
    name: "Allod's Bight",
    locations: [
      "A Captain's Repose",
      "Allod's Children",
      'Belaying Trace',
      'Blunder Bight',
      'Breath of Cetus',
      'Gangrenous Hollow',
      "Harpy's Perch",
      'Homesick',
      'The List',
      "Mercy's Wail",
      'Rumhold',
      'The Rumroad',
      'Scurvyshire',
      'The Stone Plank',
      "Titan's End",
      'The Turncoat',
      "Witch's Last Flight",
    ],
  },
  TERMINUS: {
    name: 'Terminus',
    locations: [
      'Aspisa',
      'Bay of the Ward',
      'Bloody Palm Fort',
      'Cerberus Wake',
      'Dogbone',
      "The Legion's Bounty",
      "Martyr's Fang",
      'The Phalanx',
      'The Respite',
      'Rising Loom',
      'Sever',
      'Therizó',
      'Three Siblings',
      'Thunder Plains',
      'Thunderbolt',
      "Warlord's Stead",
      'Winding Bolas',
    ],
  },
  MORGENS_CROSSING: {
    name: "Morgen's Crossing",
    locations: [
      'Allsight',
      'The Bastard Sea',
      "Bastard's Block",
      "Callum's Descent",
      'Crimson Thread',
      'Eversus',
      'Lividus',
      'Quietus',
      'Rising Calm',
      'Ultimus',
      'Velian Storm',
      'Warmonger Bay',
    ],
  },
  GODCROFTS: {
    name: 'Godcrofts',
    locations: [
      'Anchor Beach',
      'Argosa',
      'The Axehead',
      'Bagh Mòr',
      "Barreller's Bay",
      'Blackwatch',
      'Chamil Ravine',
      'Den of Thieves',
      'The Dice Road',
      'The Fleece Road',
      "Gambler's Gulf",
      'Isawa',
      'Kolas',
      'The Kris Ford',
      'Lipsia',
      'Peripti Depths',
      'Perpetua Channel',
      'Primus Trames',
      'Promithiens',
      'Protos',
      'Saegio',
      'Skodio',
      'Ursa Trail',
      'Vicit Lagoon',
    ],
  },
  TEMPEST_ISLAND: {
    name: 'Tempest Island',
    locations: [
      'Alchimio Estate',
      'Cirris Valve',
      'Eros Lagoon',
      'The Gale',
      'The Iris',
      'Isle of Psyche',
      "Liar's Haven",
      'Lost Airchal',
      'The Outwood',
      'Plana Fada',
      'Reef',
      'The Rush',
      'Sclera',
      'Stratos Valve',
      'Surge Field',
      'Surge Gate',
    ],
  },
  THE_FINGERS: {
    name: 'The Fingers',
    locations: [
      "Captain's Dread",
      'Cavitatis',
      'Cementum',
      'Fort Barley',
      "Headman's Villa",
      'Mount Talio',
      'The Old Captain',
      'Plankhouse',
      'The Routed',
      'Second Man',
      'Tears of Tethys',
      'Titancall',
      'The Tusk',
      'The Wary Nymphae',
    ],
  },
} as const;

export default MAP_INFO;
